server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/prometheus/ {
        rewrite ^/api/prometheus/(.*)$ /$1 break;
        proxy_pass http://prometheus:9090;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
